### ISSUE TITLE
influxdb-grafana-docker-compose.yml

### ISSUE THREAD

**Issue by yijia2413** [yijia2413/collections#1]
## docker-compose.yml

```
version: '3.5'
services:
  influxdb:
    image: influxdb:1.8.1-alpine
    ports:
      - "8086:8086"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --server-response --spider --quiet http://localhost:8086/ping"]
    volumes:
      - influxdb-storage:/var/lib/influxdb/
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
  
  chronograf:
    image: chronograf:latest
    ports:
      - "8888:8888"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep chronograf | grep -v grep || exit 1"]
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  influxdb-storage:
  grafana-storage:
```

Just change `users`, `passwords` with your own settings, then run `docker-compose up -d`

## enable flux
```
docker exec -it ${your_influxdb_container} influx

 cat << EOF >> /etc/influxdb/influxdb.conf
[http]
flux-enabled = true
EOF
```
